AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true

  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Style/OptionalBooleanParameter:
  Enabled: false
